### ISSUE TITLE
i can't figure out why this exception is coming. Please help??

### ISSUE THREAD

**Issue by amrik2508** [loopsocial/firework_sdk_official#2]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: <PackageName>, PID: 6994
    java.lang.IllegalStateException: view.findViewById(R.id.caption) must not be null
        at com.loopnow.fireworklibrary.adapters.VideoFeedAdapter$CustomViewHolder.<init>(VideoFeedAdapter.kt:262)
        at com.loopnow.fireworklibrary.adapters.VideoFeedAdapter.onCreateViewHolder(VideoFeedAdapter.kt:147)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6794)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:19693)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
        at android.view.View.layout(View.java:19693)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19693)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19693)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
        at android.view.View.layout(View.java:19693)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19693)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19693)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19693)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:498)
        at android.view.View.layout(View.java:19693)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:764)
        at android.view.View.layout(View.java:19693)
        at android.view.ViewGroup.layout(ViewGroup.java:6079)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2541)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2257)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6886)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
        at android.view.Choreographer.doCallbacks(Choreographer.java:841)
        at android.view.Choreographer.doFrame(Choreographer.java:772)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1015)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

**Comment by parijat-loop** [comment]
Can you post how are your XML that uses VideoFeedFragment? 
It looks like you are providing your custom layout  with attribute app:itemLayout
In the provided layout, you must have TextView with id caption and ImageView with id thumbnail

**Comment by amrik2508** [comment]
<?xml version="1.0" encoding="utf-8"?>

<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent" >

        <fragment
            android:layout_width="match_parent"
            android:layout_height="200dp"
            android:name="com.loopnow.fireworklibrary.views.VideoFeedFragment"
            app:feedLayout="horizontal"
            app:showTitle="true"
            app:appid="app-id"
            app:page_type="feed"
            app:bundle_id="com.loopnow.fireworkdemo"
            android:id="@+id/videofeed"
            android:tag="horizontal_fragment"
            app:textStyle="@style/VideoTitleStyle"
            app:imageStyle="@style/ImageStyle" />

</LinearLayout>

**Comment by parijat-loop** [comment]
Thanks for posting XML.  Your app:appid should be valid a valid app_id.
